stages:
    - test

test:
    image: cypress/browsers:node12.14.1-chrome85-ff81
    stage: test
    script:
        # install dependencies
        - yarn install --immutable --immutable-cache --check-cache

        # run Cypress tests
        - yarn run e2e:headless
