stages:
    - test

test:
    image: node:latest
    stage: test
    script:
        # install dependencies
        - yarn install --immutable --immutable-cache --check-cache

        # run Cypress tests
        - yarn run e2e:headless
