stages:
    - build

build:
    image: node:latest
    stage: build
    rules:
        # Only trigger when target merge request branch name is dev
        - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"'
    script:
        # install dependencies
        - yarn

        # build
        - yarn run build

    artifacts:
        paths:
            - ./.next
