# stages:
#     - test

# integration-testing:
#     image: cypress/browsers:node16.13.0-chrome95-ff94
#     stage: test
#     rules:
#         # Only trigger when target merge request branch name is dev
#         - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "dev"'
#     script:
#         # install dependencies
#         - yarn

#         # run Cypress tests
#         # - yarn run e2e:headless
