stages:
    - integration-testing

test:
    image: cypress/browsers:node16.13.0-chrome95-ff94
    stage: integration-testing
    script:
        # install dependencies
        - yarn install --immutable --immutable-cache --check-cache

        # run Cypress tests
        - yarn run e2e:headless
