stages:
    - test

test:
    image: node:latest
    stage: test
    script:
        # install dependencies
        - yarn install --immutable --immutable-cache --check-cache

        # start the server in the background
        - yarn run start:ci &

        # run Cypress tests
        - yarn run e2e
