stages:
    - integration-testing

integration-testing:
    image: cypress/browsers:node16.13.0-chrome95-ff94
    stage: integration-testing
    rules:
        # Only trigger when target merge request branch name is dev
        - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "dev"'
    script:
        # install dependencies
        - yarn install --immutable --immutable-cache --check-cache

        # run Cypress tests
        - yarn run e2e:headless
